INSERT INTO ADRESPONSE (ADRESPONSE_ID, AD_ID, USER_ID, RESPONSE, RESPONSE_TIME, FLAG) values (0, 0, 1, 'Message1',  NOW(), TRUE);
INSERT INTO ADRESPONSE (ADRESPONSE_ID, AD_ID, USER_ID, RESPONSE, RESPONSE_TIME, FLAG) values (1, 1, 2, 'Message2',  NOW(), FALSE);
INSERT INTO ADRESPONSE (ADRESPONSE_ID, AD_ID, USER_ID, RESPONSE, RESPONSE_TIME, FLAG) values (2, 0, 2, 'Message3',  NOW(), TRUE);
INSERT INTO ADRESPONSE (ADRESPONSE_ID, AD_ID, USER_ID, RESPONSE, RESPONSE_TIME, FLAG) values (3, 0, 2, 'Message4',  NOW(), FALSE);
INSERT INTO ADRESPONSE (ADRESPONSE_ID, AD_ID, USER_ID, RESPONSE, RESPONSE_TIME, FLAG) values (4, 0, 1, 'Message5',  NOW(), TRUE);
