sudo: required
dist: trusty

matrix:
  include:
    - language: java
      jdk: openjdk11
      addons:
        sonarcloud:
          organization: "unige-pinfo-2019" # the key of the org you chose at step #3
      script:
        - mvn sonar:sonar -Dsonar.projectKey=unige-pinfo-2019_PInfo3 -Dsonar.organization=unige-pinfo-2019 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=b89cca69d31bf42b2d5c4ec913c8ae8f1f84f450


    - language: java
      jdk: openjdk11
      services:
        - docker
      before_script:
        - cd classads-service
      script:
        - mvn clean package
        - docker build -t 2019pinfo3/classads-service .
      after_success:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push 2019pinfo3/classads-service:latest


    - language: java
      jdk: openjdk11
      services:
        - docker
      before_script:
        - cd user-service
      script:
        - mvn clean package
        - docker build -t 2019pinfo3/user-service .
      after_success:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push 2019pinfo3/user-service:latest

    - language: node_js
      node_js:
        - "11"
      services:
        - docker
      before_script:
        - cd web-ui
        - npm rebuild node-sass
        - npm install dependencies
      script:
        - npm run build
        - docker build -t 2019pinfo3/web-ui .
      after_success:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push 2019pinfo3/web-ui:latest
