
matrix:
  include:
    - language: java
      jdk: openjdk11
      services:
        - docker
      before_script:
        - cd classads-service
      script:
        - mvn clean package
        - docker build -t pinfo3/classads-service .

    - language: java
      jdk: openjdk11
      services:
        - docker
      before_script:
        - cd user-service
      script:
        - mvn clean package
        - docker build -t pinfo3/user-service .

    - language: node_js
      node_js:
        - "11"
      services:
        - docker
      before_script:
        - cd frontend
        - npm rebuild node-sass
        - npm install dependencies
      script:
        - npm run build
        - docker build -t pinfo3/frontend .
