version: "3.5"

services:

  # classads service is for posting a classified ad
  classads-database:
    image: postgres:10
    container_name: classads-database
    hostname: classads-database
    networks:
     - backend-network
    environment:
      POSTGRES_USER: ad
      POSTGRES_PASSWORD: ad
      POSTGRES_DB: classadsdb
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "ad", "-d", "classadsdb"]
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - pgdata-classads:/var/lib/postgresql/data
    restart: on-failure
    stdin_open: true
    tty: true

  classads-service:
    container_name: classads-service
    image: 2019pinfo3/classads-service:latest
    hostname: classads-service
    networks:
      - backend-network
    ports:
      - "8081:8080"
    environment:
      THORNTAIL_DATASOURCES_DATA_DASH_SOURCES_CLASSADSDS_CONNECTION_DASH_URL: "jdbc:postgresql://classads-database:5432/classadsdb"
      THORNTAIL_DATASOURCES_DATA_DASH_SOURCES_CLASSADSDS_DRIVER_DASH_NAME: 'postgresql'   
      THORNTAIL_DATASOURCES_DATA_DASH_SOURCES_CLASSADSDS_USER_DASH_NAME: 'ad'
      THORNTAIL_DATASOURCES_DATA_DASH_SOURCES_CLASSADSDS_PASSWORD: 'ad'
    depends_on:
      - classads-database

  # user service is for logging in users
  user-service:
    container_name: user-service
    image: 2019pinfo3/user-service:latest
    hostname: user-service
    networks:
      - backend-network
    ports:
      - "8082:8080"

  # web-ui is the UI through which the user interacts with the services
  web-ui:
    container_name: web-ui
    image: 2019pinfo3/web-ui:latest
    hostname: web-ui
    networks:
      - frontend-network
    ports:
      - "8083:8081"
    depends_on:
       - classads-service
       - user-service

volumes:
  pgdata-classads:

networks:
  backend-network:
    driver: bridge
  frontend-network:
    driver: bridge
