version: "3.5"

services:

  # classads service is for posting a classified ad
  classads-service:
    container_name: classads-service
    image: 2019pinfo3/classads-service:latest
    hostname: classads-service
    networks:
      - backend-network
    ports:
      - "8081:8080"

  # user service is for logging in users
  user-service:
    container_name: user-service
    image: 2019pinfo3/user-service:latest
    hostname: user-service
    networks:
      - backend-network
    ports:
      - "8082:8080"

  # web-ui is the UI through which the user interacts with the services
  web-ui:
    container_name: web-ui
    image: 2019pinfo3/web-ui:latest
    hostname: web-ui
    networks:
      - frontend-network
    ports:
      - "8083:8081"
    depends_on:
       - classads-service
       - user-service

networks:
  backend-network:
    driver: bridge
  frontend-network:
    driver: bridge
