version: "2.1"

services:

  iam-db:
   image: postgres:10
   container_name: iam-db
   hostname: iam-db
   networks:
    - backend-network
   environment:
     POSTGRES_USER: admin
     POSTGRES_PASSWORD: password
     POSTGRES_DB: keycloakdb
   healthcheck:
     test: ["CMD", "pg_isready", "-U", "admin", "-d", "keycloakdb"]
     interval: 30s
     timeout: 30s
     retries: 3
   restart: on-failure
   stdin_open: true
   tty: true
   volumes:
     - pgdata-iam:/var/lib/postgresql/data


  iam:
    image: jboss/keycloak:5.0.0
    container_name: iam
    hostname: iam
    networks:
     - gateway-network
     - backend-network
    restart: on-failure
    ports:
      - 8080:8080
    volumes:
      - ./iam-config/:/tmp/iam-config
      - ./iam-config/pinfo3:/opt/jboss/keycloak/themes/pinfo3
      - ./iam-config/standalone.xml:/opt/jboss/keycloak/standalone/configuration/standalone.xml
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=password
      - DB_VENDOR=postgres
      - DB_USER=admin
      - DB_PASSWORD=password
      - DB_ADDR=iam-db
      - DB_PORT=5432
      - DB_DATABASE=keycloakdb
      - PROXY_ADDRESS_FORWARDING=true
      - KEYCLOAK_IMPORT=/tmp/iam-config/realm-export.json
    depends_on:
       iam-db :
         condition: service_healthy

volumes:
  pgdata-kong:
  pgdata-iam:

networks:
  gateway-network:
     external:
        name: docker_compose_frontend-network
  backend-network:
     external:
        name: docker_compose_backend-network
